### ISSUE TITLE
Dynamic binding

### ISSUE THREAD

**Issue by chmln** [blue0728/vue-count-down#1]
Hello,

Thank you for this directive! :+1: 
But looks like it doesn't work when you bind the date string to a value.
Here's what I have

``` jade
    span(
        :v-time-down="set.due"
    )
```

Where set.due is a date string. 

![screenshot_2016-07-12_18-05-23](https://cloud.githubusercontent.com/assets/11352152/16785283/3d0ccb14-485b-11e6-92ab-44116f53b78b.png)

There is no output and the console is also empty

**Comment by blue0728** [comment]
Sorry, I forgot to update the document.

``` html
<p v-count-down="'2016-07-02 15:08:00'"></p>
<p v-count-down="'2016/07/02 15:08:00'"></p>
```
